name: Sync Dependabot Config
on:
  push:
    branches:
      - main
  paths:
    - 'sync/dependabot.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central repo
        uses: actions/checkout@v4

      - name: Copy config to other repos
        run: |
          for repo in "estetsenko/first" "estetsenko/second"; do
            gh repo clone $repo
            cp sync/dependabot.yml $repo/.github/
            cd $repo
            git add .github/dependabot.yml
            git commit -m "Update Dependabot config"
            git push
            cd ..
          done
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}