name: Sync Dependabot Config
on:
  push:
    branches:
      - staging
    paths:
      - 'dependabot.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central repo
        uses: actions/checkout@v4
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'dependabot.yml'
          destination_repo: 'estetsenko/first'
          destination_folder: '.github'
          user_email: 'i@estetsenko.com'
          user_name: 'estetsenko'
          commit_message: 'A custom message for the commit'
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}