name: Sync Dependabot Config
on:
  push:
    branches:
      - main
    paths:
      - 'dependabot.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central repo
        uses: actions/checkout@v4

      - name: Copy config to other repos
        run: |
          for repo in "estetsenko/first" "estetsenko/second"; do
            gh repo clone $repo $repo
            mkdir $repo/.github/
            cp dependabot.yml $repo/.github/
            cd $repo
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
            git add .github/dependabot.yml
            git commit -m "Update Dependabot config"
            git push
            cd ..
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}