name: Sync Dependabot Config
on:
  push:
    branches:
      - staging
    paths:
      - 'dependabot.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central repo
        uses: actions/checkout@v4
      - name: Copy config to other repos
        run: |
          for repo in "estetsenko/first" "estetsenko/second"; do
            gh repo clone $repo $repo
            mkdir $repo/.github/
            cp dependabot.yml $repo/.github/
            cd $repo
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add .github/dependabot.yml
            branch="sync-$RANDOM"
            git switch -c $branch
            git commit -m "Update Dependabot config"
            git push --set-upstream origin $branch
            gh pr create -B main -H $branch -f -R $repo
            cd ..
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}